import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Users, Ticket, ScanLine, CalendarClock, LogOut, Search, Plus, X, ShieldCheck, Clock3, ArrowUpRight } from 'lucide-react';
import './styles.css';

const initialVisitors = [{ id: 1, name: 'Jordan Lee', company: 'Acme Labs', host: 'Maya Host', purpose: 'Product meeting', status: 'Checked in', time: '09:42 AM' }, { id: 2, name: 'Priya Shah', company: 'Nimble Co.', host: 'Maya Host', purpose: 'Design review', status: 'Expected', time: '11:30 AM' }, { id: 3, name: 'Diego Ruiz', company: 'Clearwater', host: 'Ava Admin', purpose: 'Vendor delivery', status: 'Checked out', time: '08:15 AM' }];
const nav = [{ icon: LayoutDashboard, label: 'Overview' }, { icon: Users, label: 'Visitors' }, { icon: CalendarClock, label: 'Appointments' }, { icon: Ticket, label: 'Passes' }, { icon: ScanLine, label: 'Scan pass' }];
function App() { const [page, setPage] = useState('Overview'); const [visitors, setVisitors] = useState(initialVisitors); const [modal, setModal] = useState(false); const [query, setQuery] = useState(''); const [toast, setToast] = useState('');
 const notify = msg => { setToast(msg); setTimeout(() => setToast(''), 2800); };
 const addVisitor = data => { setVisitors([{ id: Date.now(), ...data, status: 'Expected', time: 'Just now' }, ...visitors]); setModal(false); notify(`${data.name} has been registered and is ready for a pass.`); };
 const filtered = visitors.filter(v => `${v.name} ${v.company}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><aside><div className="brand"><span className="brand-mark"><ShieldCheck size={20}/></span><span>visitflow</span></div><div className="workspace">WORKSPACE</div>{nav.map(({icon: Icon,label}) => <button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon size={18}/>{label}</button>)}<div className="sidebar-bottom"><div className="user-avatar">AA</div><div><b>Ava Admin</b><small>Administrator</small></div><LogOut size={17}/></div></aside><main><header><div><p className="eyebrow">MONDAY, OCTOBER 5</p><h1>{page === 'Overview' ? 'Good morning, Ava.' : page}</h1><p className="sub">{page === 'Overview' ? 'Here is what is happening at your workplace today.' : 'Manage your visitor experience with confidence.'}</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> New visitor</button></header>{page==='Overview'?<Overview visitors={visitors} setPage={setPage}/>:page==='Visitors'?<Visitors visitors={filtered} query={query} setQuery={setQuery} notify={notify}/>:<FeaturePage page={page} visitors={visitors} notify={notify}/>}</main>{modal&&<VisitorModal onClose={()=>setModal(false)} onSave={addVisitor}/>} {toast&&<div className="toast"><ShieldCheck size={18}/>{toast}</div>}</div> }
function Overview({visitors,setPage}) { const checked=visitors.filter(v=>v.status==='Checked in'); return <><section className="metrics"><Metric icon={Users} value={visitors.length+21} label="Total visitors" note="12% from last week"/><Metric icon={ScanLine} value={checked.length} label="Currently on-site" note="Live occupancy"/><Metric icon={CalendarClock} value={visitors.filter(v=>v.status==='Expected').length+5} label="Expected today" note="Next arrival 11:30 AM"/></section><section className="grid"><div className="card wide"><div className="card-title"><div><h2>Today’s visitors</h2><p>A live view of arrivals and appointments.</p></div><button className="text-btn" onClick={()=>setPage('Visitors')}>View all <ArrowUpRight size={16}/></button></div><VisitorTable visitors={visitors}/></div><div className="card activity"><div className="card-title"><div><h2>Recent activity</h2><p>Latest access events</p></div></div>{checked.length ? <Activity name={checked[0].name} text="checked in at Main Lobby" time={checked[0].time}/>:null}<Activity name="Diego Ruiz" text="checked out from Main Lobby" time="10:03 AM"/><Activity name="Priya Shah" text="was pre-registered" time="09:26 AM"/></div></section></> }
function Metric({icon:Icon,value,label,note}) { return <div className="metric"><div className="metric-icon"><Icon size={21}/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div> }
function Visitors({visitors,query,setQuery,notify}) { return <section className="card"><div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by visitor or company"/></div><button className="secondary">All statuses</button><button className="secondary">Today</button></div><VisitorTable visitors={visitors} onAction={v=>notify(`${v.name}'s pass is ready to scan.`)}/></section> }
function FeaturePage({page,visitors,notify}) { if(page==='Scan pass') return <section className="card scanner"><ScanLine size={38}/><h2>Scan or enter a visitor pass</h2><p className="sub">Use a camera scanner in production, or enter a pass code to record check-in/check-out.</p><div className="scan-entry"><input placeholder="VP-DEMO2026"/><button className="primary" onClick={()=>notify('Pass scanned. Check-in/check-out event recorded.')}>Process pass</button></div></section>; if(page==='Appointments') return <section className="card"><div className="card-title"><div><h2>Pre-registrations awaiting approval</h2><p>Hosts approve visits before a pass is issued.</p></div><button className="primary" onClick={()=>notify('Invitation created and notification queued.')}>Create invite</button></div><VisitorTable visitors={visitors.filter(v=>v.status==='Expected')} onAction={v=>notify(`${v.name}'s appointment approved and email notification queued.`)}/></section>; return <section className="card"><div className="card-title"><div><h2>Digital passes</h2><p>QR-coded credentials and printable PDF badges.</p></div><button className="primary" onClick={()=>notify('A QR pass and PDF badge were issued.')}>Issue pass</button></div><VisitorTable visitors={visitors} onAction={v=>notify(`PDF badge for ${v.name} is ready for download.`)}/><div className="report-note">Security staff can scan each QR pass at the front desk. Administrators can export check-in/check-out logs from <code>/api/reports/check-logs.csv</code>.</div></section> }
function VisitorTable({visitors,onAction}) { return <div className="table-wrap"><table><thead><tr><th>VISITOR</th><th>HOST</th><th>PURPOSE</th><th>STATUS</th><th>TIME</th><th></th></tr></thead><tbody>{visitors.map(v=><tr key={v.id}><td><div className="person"><span>{v.name.split(' ').map(x=>x[0]).join('')}</span><div><b>{v.name}</b><small>{v.company}</small></div></div></td><td>{v.host}</td><td>{v.purpose}</td><td><em className={v.status.toLowerCase().replace(' ','-')}>{v.status}</em></td><td>{v.time}</td><td><button className="dots" onClick={()=>onAction?.(v)}>•••</button></td></tr>)}</tbody></table></div> }
function Activity({name,text,time}) { return <div className="activity-row"><span className="activity-icon"><Clock3 size={16}/></span><div><b>{name}</b> {text}<small>{time}</small></div></div> }
function VisitorModal({onClose,onSave}) { const [form,setForm]=useState({name:'',company:'',host:'Maya Host',purpose:''}); const change=e=>setForm({...form,[e.target.name]:e.target.value}); return <div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();onSave(form)}}><button type="button" className="close" onClick={onClose}><X/></button><p className="eyebrow">REGISTER VISITOR</p><h2>Create a visitor record</h2><p className="sub">Add the details, then issue a secure digital pass.</p><label>Full name<input autoFocus name="name" required value={form.name} onChange={change} placeholder="e.g. Jordan Lee"/></label><label>Company<input name="company" required value={form.company} onChange={change} placeholder="e.g. Acme Labs"/></label><label>Host<select name="host" value={form.host} onChange={change}><option>Maya Host</option><option>Ava Admin</option></select></label><label>Purpose<input name="purpose" required value={form.purpose} onChange={change} placeholder="e.g. Product meeting"/></label><button className="primary full" type="submit">Register and issue pass</button></form></div> }
createRoot(document.getElementById('root')).render(<App/>);
